apiVersion: v1
kind: Secret
metadata:
  name: blacklist-secrets
  namespace: blacklist
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres" 
  CREDENTIAL_MASTER_KEY: "change_me_to_your_master_key"
