apiVersion: v1
kind: Service
metadata:
  name: blacklist-redis
  namespace: blacklist
  labels:
    app: blacklist-redis
spec:
  ports:
  - port: 6379
    name: redis
  selector:
    app: blacklist-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blacklist-redis
  namespace: blacklist
spec:
  selector:
    matchLabels:
      app: blacklist-redis
  replicas: 1
  template:
    metadata:
      labels:
        app: blacklist-redis
    spec:
      containers:
      - name: redis
        image: ${REGISTRY_DOMAIN}/blacklist-redis:latest
        ports:
        - containerPort: 6379
          name: redis
        envFrom:
        - configMapRef:
            name: blacklist-config
        volumeMounts:
        - name: redis-data
          mountPath: /data
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: redis-data
        emptyDir: {}
